contact_links:
  - name: ðŸ¤” FAQ
    url: https://github.com/saucelabs/testrunner-toolkit/blob/master/docs/FAQS.md
    about: Before filing an issue, please consult the FAQ first. You just might find your answer right there!
